### ISSUE TITLE
Missing `shinythemes` dependency

### ISSUE THREAD

**Issue by simon-smart88** [collaborativebioinformatics/VariantSurvival#32]
When I installed per your instructions I got the error `there is no package called ‘shinythemes’`. You should add this to your DESCRIPTION as an import.

**Comment by simon-smart88** [comment]
Hi Marina, I already installed shinythemes and got it running so not much point reinstalling (I just wanted to have a quick look) but that merge looks like it should deal with this and #33 too! Thanks

**Comment by Krannich479** [comment]
Thanks for reporting. This is indeed implemented in the new version 0.2.0.

I leave this here for reference:
https://github.com/collaborativebioinformatics/VariantSurvival/blob/45d7e19521811f0c8b544e5904eded2936ebd8b7/VariantSurvival_package/DESCRIPTION#L33

Since it is fixed on your side and implemented now I'll close this issue.
